export default {
  id: "claude",
  rename: {},
  allow: [
    "name",
    "displayName",
    "description",
    "version",
    "author",
    "homepage",
    "repository",
    "license",
    "keywords",
    "skills",
    "commands",
    "agents",
    "hooks",
    "mcpServers",
    "outputStyles",
    "lspServers",
  ],
  lists: ["keywords"],
  transforms: [],
  output: {
    path: ".claude-plugin/plugin.json",
    format: "json",
    pretty: true,
  },
};
