export default {
  id: "cursor",
  rename: {},
  allow: [
    "name",
    "displayName",
    "description",
    "version",
    "author",
    "homepage",
    "repository",
    "license",
    "keywords",
    "logo",
    "rules",
    "skills",
    "agents",
    "commands",
    "hooks",
    "mcpServers",
  ],
  lists: ["keywords"],
  transforms: [],
  output: {
    path: ".cursor-plugin/plugin.json",
    format: "json",
    pretty: true,
  },
};
